version: '3.8'

services:
  mongo:
    image: mongo:4.4
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db


  api:
    image: engelbb/proyecto1_fase1-api:latest
    container_name: api
    ports:
      - "8080:4000"
    depends_on:
      - mongo
    restart: always

  monitor:
    image: engelbb/proyecto1_fase1-monitor:latest
    container_name: monitor
    depends_on:
      - api
    volumes:
      - /proc:/proc
    environment:
      - API_URL=http://api:4000/api/metricas
    restart: always

  frontend:
    image: engelbb/proyecto1_fase1-frontend:latest
    container_name: frontend
    ports:
      - "5173:80"
    depends_on:
      - api

volumes:
  mongo_data:







     